### ISSUE TITLE
Impossible to execute a get request

### ISSUE THREAD

**Issue by notiles** [pusher/pusher-http-node#15] opened 2015-05-20 09:27 UTC
When I try to get channels list, I've got this error:

_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Request.start (/var/www/WEB/tuborg_push/node_modules/pusher/node_modules/request/request.js:812:30)
    at Request.end (/var/www/WEB/tuborg_push/node_modules/pusher/node_modules/request/request.js:1494:28)
    at end (/var/www/WEB/tuborg_push/node_modules/pusher/node_modules/request/request.js:550:16)
    at /var/www/WEB/tuborg_push/node_modules/pusher/node_modules/request/request.js:564:9
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)

The code I try to execute is really simple:

var config = require('./config.js');
var Pusher = require('pusher');

var pusher = new Pusher({ appId: config.APP_ID, key: config.APP_KEY, secret: config.APP_SECRET });
pusher.get({ path: '/channels', params: {} }, function(error, request, response) {
        if (response.statusCode === 200) {
            var result = JSON.parse(response.body);
            var channelsInfo = result.channels;
        }
});

Node version : 0.12.1

**Comment by leggetter** [comment] 2015-05-20 12:33
This looks like a duplicate of https://github.com/pusher/pusher-http-node/issues/12 Could you please let us know what version of the Pusher library are you using?

**Comment by notiles** [comment] 2015-05-20 13:54
"name": "pusher",
  "description": "Node.js client to interact with the Pusher REST API",
  "version": "1.0.4",
  "author": {
    "name": "Pusher",
    "email": "support@pusher.com"
  },

**Comment by leggetter** [comment] 2015-05-20 13:56
Thanks, @notiles. You're on v1.0.4 and the bug you have identified was fixed in #13 and released in v1.0.6. So, please update to this version of the library.

**Closed by leggetter** 2015-05-20 13:56 UTC

**Comment by notiles** [comment] 2015-05-20 14:03
perfect! it works!
thanks a lot
